spring:
  application:
    name: spring-data-jpa

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

    hibernate:
      ddl-auto: update

    show-sql: true
